# Generated by Django 4.2.2 on 2023-07-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=200)),
                ('views', models.PositiveIntegerField()),
                ('subscribers', models.PositiveIntegerField()),
                ('monetized', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='VideoGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('videos', models.ManyToManyField(to='main_app.video')),
            ],
        ),
    ]
