# Generated by Django 4.2.2 on 2023-07-14 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode_id', models.CharField(max_length=255, unique=True)),
                ('comment', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('words_file', models.FileField(upload_to='media/')),
                ('min_view_count', models.IntegerField(default=0)),
                ('shorts', models.BooleanField(default=False)),
                ('max_sub_count', models.IntegerField(default=0)),
                ('proxy_address', models.CharField(blank=True, max_length=255, null=True)),
                ('proxy_login', models.CharField(blank=True, max_length=255, null=True)),
                ('proxy_pass', models.CharField(blank=True, max_length=255, null=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='parser_service.mode')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
