# Generated by Django 4.2.2 on 2023-07-16 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personsettings',
            name='max_sub_count',
            field=models.IntegerField(default=20000, validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(1000000)]),
        ),
        migrations.AlterField(
            model_name='personsettings',
            name='min_view_count',
            field=models.IntegerField(default=100000, validators=[django.core.validators.MinValueValidator(20000), django.core.validators.MaxValueValidator(1000000)]),
        ),
    ]
